Repository hapinessjs/rabbit-module, pull requests merged in 2018-04, with the labels that each got.

#27 release(version): v1.3.2
  package-lock.json
  package.json
  src/module/register-annotations.ts
Labels: bug

#28 Channel refactor
  package-lock.json
  package.json
  src/module/managers/channel-manager.ts
  src/module/managers/channel-store.ts
  src/module/managers/connection-manager.ts
  src/module/managers/queue-manager.ts
  src/module/register-annotations.ts
  test/mocha.opts
  test/mocks/Channel.ts
  test/mocks/ConnectionManager.ts
  test/unit/extension/init-extension.test.ts
  test/unit/managers/channel.test.ts
  test/unit/managers/queue.test.ts
Labels: enhancement

#29 release(version): v1.4.0
  package-lock.json
  package.json
  src/module/managers/channel-manager.ts
  src/module/managers/channel-store.ts
  src/module/managers/connection-manager.ts
  src/module/managers/queue-manager.ts
  src/module/register-annotations.ts
  test/mocha.opts
  test/mocks/Channel.ts
  test/mocks/ConnectionManager.ts
  test/unit/extension/init-extension.test.ts
  test/unit/managers/channel.test.ts
  test/unit/managers/queue.test.ts
Labels: enhancement

#30 Channel refactor
  src/module/managers/channel-manager.ts
  src/module/managers/connection-manager.ts
  src/module/managers/message-store.ts
  src/module/managers/queue-manager.ts
Labels: enhancement

#31 release(version): v1.4.0
  src/module/managers/channel-manager.ts
  src/module/managers/connection-manager.ts
  src/module/managers/message-store.ts
  src/module/managers/queue-manager.ts
Labels: dependencies, enhancement
